# Generated by Django 5.1.5 on 2025-02-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major_2',
            field=models.CharField(max_length=50),
        ),
    ]
