# Generated by Django 5.1.5 on 2025-02-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='answer4',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
