# Generated by Django 5.1.5 on 2025-02-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliance', '0002_alter_application_answer4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='answer4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='portfolio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
